### ISSUE TITLE
build-essential not available early on?

### ISSUE THREAD

**Issue by yeago** [whiskerlabs/ansible-python#2]
TASK: [whiskerlabs.python | configure a makefile for readline 6.2] ************
failed: [www2] => {"changed": true, "cmd": "./configure --disable-shared --enable-static --prefix=/tmp/python/readline", "delta": "0:00:00.191346", "end": "2015-10-30 22:59:56
.356111", "rc": 1, "start": "2015-10-30 22:59:56.164765", "warnings": []}
stderr: configure: error: in `/tmp/python/readline-6.2':
configure: error: no acceptable C compiler found in $PATH
See`config.log' for more details.
stdout: checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu

Beginning configuration for readline-6.2 for x86_64-unknown-linux-gnu

checking whether make sets $(MAKE)... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no

FATAL: all hosts have already failed -- aborting

**Comment by yeago** [comment]
i do notice that build essential gets installed later than this rule, i install it beforehand manually and it works fine

**Comment by evnm** [comment]
Good catch. I moved the package-installation task into `main.yml` prior to the inclusion of `readline.yml`. Thanks for the bug report!
