### ISSUE TITLE
readlines6.2 timeout

### ISSUE THREAD

**Issue by yeago** [whiskerlabs/ansible-python#6]
Pretty strange

TASK: [whiskerlabs.python | download source tarballs] ************************\* 
<45.79.9.93> ESTABLISH CONNECTION FOR USER: root
<45.79.9.93> REMOTE_MODULE get_url dest=/tmp/python/readline-6.2.tar.gz url=ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz
<45.79.9.93> EXEC sshpass -d7 ssh -C -vvv -o ForwardAgent=yes -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o User=root -o ConnectTimeout=10 45.79.9.93 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
failed: [neomonolith] => (item={'url': u'ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz', 'dest': u'/tmp/python/readline-6.2.tar.gz'}) => {"dest": "/tmp/python/readline-6.2.tar.gz", "failed": true, "item": {"dest": "/tmp/python/readline-6.2.tar.gz", "url": "ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz"}, "response": "Request failed: <urlopen error ftp error: timed out>", "state": "absent", "status_code": -1, "url": "ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz"}

Resolving ftp.cwru.edu (ftp.cwru.edu)... 52.87.62.244, 50.17.163.19
Connecting to ftp.cwru.edu (ftp.cwru.edu)|52.87.62.244|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/bash ... done.
==> SIZE readline-6.2.tar.gz ... 2277926
==> PASV ... 

couldn't connect to 172.22.8.106 port 32086: Connection timed out
Retrying.

**Comment by yeago** [comment]
just an FYI. I updated this lib and it worked okay.

**Comment by evnm** [comment]
Yes, this issue was fixed in [v0.0.3](https://github.com/whiskerlabs/ansible-python/releases/tag/v0.0.3).
